// The tables DokaanBondhu's read-only role may read (spec 5.3). The custom migration grants exactly these.
export const AI_READABLE_TABLES = [
  "parts",
  "part_numbers",
  "part_aliases",
  "categories",
  "brands",
  "vehicles",
  "fitments",
  "stock_levels",
  "stock_movements",
  "customers",
  "customer_ledger",
  "sales",
  "sale_items",
  "sale_payments",
  "customer_payments",
  "returns",
  "return_items",
  "suppliers",
  "supplier_ledger",
  "supplier_payments",
  "purchases",
  "purchase_items",
  "accounts",
  "account_transactions",
  "daily_closings",
  "expense_categories",
  "expenses",
  "cheques",
] as const;
